name: build

on:
  push:
    branches:
      - main
  pull_request:

env:
  TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe #v4.1.0
        with:
          go-version-file: 'go.mod'
      - name: Setup tool
        run: |
          go install github.com/Azure/mapotf@latest
          go install github.com/lonegunmanb/avmfix@latest
      - name: Run tests
        run: go test -v github.com/lonegunmanb/TerraformConfigWelder/...